
version: '3.8'

services:
  db:
    image: postgres:13
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./.data:/var/lib/postgresql/data

  python:
    build:
      context: ./dsl
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./dsl:/app
      - ./.pybaseball:/app/.pybaseball/cache
    working_dir: /app

